### ISSUE TITLE
Definir variables de configuracion

### ISSUE THREAD

**Issue by erickjosue8916** [erickjosue8916/habanerocss#4]
Definir variables de configuracion nos permitira generar configuracion y ediciones mucho mas rapidas al framework y una personalizacion mucho mayor a quien la utilize

```css
/* Configuracion de variables globales para el framework */
:root {
    --primary-color: #000;
    --secondary-color: #000;
    --accent-color: #000;
    --danger-color: #000;
    --success-color: #000;
    --font-type: arial;
}
/* Uso de las variables */
.texto {
    color: var(--primary-color)
}
```
