### ISSUE TITLE
clases modificadoras

### ISSUE THREAD

**Issue by erickjosue8916** [erickjosue8916/habanerocss#5]
Definir clases modificadores aplicables a cualquier componente y con un objetivo especifico nos permitira personalizar gran parte del codigo
```css
/* Clases de apoyo */
.text-red { color: #f00 }
.bold { font-weight: bold }
.underline { text-decoration: none }
.box-shadow { box-shadow: 5px 5px 10px #000}
.text-shadow { text-shadow: 5px 5px 10px #00}
```
Si queremos sacar un texto con color rojo, en negrita y sombreado, podriamos recurrir a estas clases sin necesidad de modificar el css
```html
<span class="text-red bold text-shadow">
    texto
</span>
